version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-dev
    volumes:
     - ../../:/go/src/github.com/sundogrd/creator-service
    environment:
      - GO111MODULE=on
